### ISSUE TITLE
Form errors are not cleared when switching presets

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-ondd#11]
When user submits custom settings that contain errors, the fields with errors are marked. When user then selects another preset, and then switches back to custom settings, the fields with errors are still marked even though the data has changed. When user switches to a preset other than "Select a satellite", and form data is filled in from the preset data, the errors should be cleared.

**Comment by ben-en** [comment]
Fixed in 03ac2a0f4b948afe007682b5f9681ce8f4d6ee5c
