### ISSUE TITLE
Long filenames overflow

### ISSUE THREAD

**Issue by ben-en** [Outernet-Project/librarian-ondd#22]
![20160127_072839](https://cloud.githubusercontent.com/assets/11149483/12618285/0ff255c0-c4c8-11e5-9ec6-4a61d2c63ad9.png)

Long file names overflow under the update button on the first two listed carousels.

**Comment by goodbadwolf** [comment]
The fix is in develop, hasn't been merged with master yet.

**Comment by ben-en** [comment]
Ah, ok. Didn't see it as a listed issue. For the record, the issue was noticed on 2.5a3. 

2.5a3 was created from outerbox d1e99e6898c5bc155a10ee316fcce2223d3c1b8d, with notifications at 8fd53bd4b3fb337ebe48e488e1293b0886849dbd and diskspace at c073419b71d5a8eea8bd69a8c71dc5dfc1e75b8f.
